@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title C4 Component Diagram - Triptop

System_Boundary("Triptop", "Triptop Applicatie") {
    System("IdentityProvider", "Identity Provider", "OAuth authenticatie")

    System("BetalingController", "BetalingController", "API Endpoint voor betalingen")
    System("BetalingService", "BetalingService", "Behandelt de logica voor betalingen")
    System("BetalingRepository", "BetalingRepository", "Repository klasse voor betalingen")

    System("BoekingController", "BoekingController", "API Endpoint voor boekingen")
    System("BoekingService", "BoekingService", "Behandelt de logica voor boekingen")
    System("BoekingRepository", "BoekingRepository", "Repository klasse voor boekingen")
}

Rel(BetalingController, BetalingService, "Verwerkt betalingslogica")
Rel(BetalingService, BetalingRepository, "")

Rel(BoekingController, BoekingService, "Verwerkt boekingslogica")
Rel(BoekingService, BoekingRepository, "")

@enduml
