@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title C4 Component Diagram - Triptop

System_Ext("NS", "NS", "API van NS")
System_Ext("KLM", "KLM", "API van KLM")

System_Boundary("Triptop", "Triptop Applicatie") {
    System("BoekingController", "BoekingController", "API Endpoint voor boekingen")
    System("BoekingService", "BoekingService", "Behandelt de logica voor boekingen")
    System("BoekingRepository", "BoekingRepository", "Repository klasse voor boekingen")
}

SystemDb("Database", "Database", "")

Rel(BoekingController, BoekingService, "Verwerkt boekingslogica")
Rel(BoekingService, BoekingRepository, "")
Rel(BoekingService, NS, Gebruikt)
Rel(BoekingService, KLM, Gebruikt)
Rel(BoekingRepository, "Database", Leest/schrijft)


@enduml
