@startuml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml


Container(singlePageApp, "Single page applicatie", "Container: JavaScript and React", "Single page applicatie voor het samenstellen van een reis")

System_Boundary(c1, "Rest API") {
Component(identity_controller, "Identity controller", "Spring rest controller")
Component(identity_service, "Identity service", "Spring service")
Component(identity_dao, "Identity dao", "Spring repository")
}

Container_Ext(identityProviderService, "Identity provider service", "Service zoals Google of Facebook voor het inloggen")
ContainerDb(database, "Database", "Container: ?", "Database voor het opslaan en ophalen van gegevens")


Rel(singlePageApp, identity_controller, "Maakt API verzoek naar", "JSON/HTTP")
Rel(identity_controller, identity_service, "Gebruikt")
Rel(identity_service, identity_dao, "Gebruikt")


Rel(singlePageApp, identityProviderService, "Geneert een token via", "?")
Rel(identity_service, identityProviderService, "Controleert de token via", "?")
Rel(identity_dao, database, "leest of schrijft naar", "?")

@enduml