@startuml

!include  https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

SHOW_PERSON_OUTLINE()

Person("Reiziger", "Reiziger", "Klant")
Person("Reisagent", "Reisagent", "Support")

System("Triptop", "Triptop", "Zelfstandig reisplanning en beheer")

System_Ext("Accommodatie","Accommodatie (Airbnb, booking, etc)", "Biedt verhuur opties aan van accommodaties")
System_Ext("VervoerVerhuur","Vervoer verhuur (Sixt, hertz, etc)", "Biedt verhuur opties voor vervoer")
System_Ext("VervoerMaatschappij","Vervoer maatschappij (KLM, NS, etc)", "Biedt tickets aan aan van vervoersmaatschappijen")
System_Ext("Activiteiten","Activiteiten GetYourGuide, Tripadvisor, etc)", "Biedt activiteiten aan")
System_Ext("IdentityProvider","IdentityProvider (Apple, Google, etc)", "Biedt opties aan om je te identificeren")
System_Ext("EtenEnDrinken","Eten en drinken (UberEats, Eet.nu, etc)", "Biedt opties aan om eten te bestellen")
System_Ext("PaymentProvider","PaymentProvider (Adyen, PayPal, etc)", "Biedt opties aan om te betalen")

Rel("Reiziger", "Triptop", "Het samenstellen, boeken, annuleren en aanpassen van een reis")
Rel("Reisagent", "Triptop", "Verleent support aan reizigers")
Rel("Triptop", "Accommodatie", "Biedt verhuur opties aan van accommodaties")
Rel("Triptop", "VervoerVerhuur", "Biedt verhuur opties voor vervoer")
Rel("Triptop", "VervoerMaatschappij", "Biedt tickets aan aan van vervoersmaatschappijen")
Rel("Triptop", "Activiteiten", "Biedt activiteiten aan")
Rel("Triptop", "IdentityProvider", "Biedt opties aan om je te identificeren")
Rel("Triptop", "EtenEnDrinken", "Biedt opties aan om eten te bestellen")
Rel("Triptop", "PaymentProvider", "Biedt opties aan om te betalen")

@enduml