@startuml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

SHOW_PERSON_OUTLINE()
LAYOUT_WITH_LEGEND()

Person(klant, "Reiziger", "Stelt reis samen en boekt deze")
Person(reisAgent, "ReisAgent", "Helpt klant met het samenstellen van een reis")

System_Boundary(tripTopApp, "Triptop App") {
Container(frontend, "Frontend", "Container: JavaScript and React", "Website voor het samenstellen van een reis")
Container(backend, "Backend", "Container: Java and Spring Data", "Server voor het verwerken van data")
ContainerDb(database, "Database", "Container: ?", "Database voor het opslaan en ophalen van gegevens")
}

System_Ext(overnachtingService, "Overnachting service", "Service zoals booking.com of AirBnB voor het boeken van een overnachting")
System_Ext(vervoerService, "Vervoer service", "Service zoals NS of KLM voor het vervoer naar de bestemming")
System_Ext(activiteitService, "Activiteit service", "Service zoals GetYourGuide voor het plannen van excursies/activiteiten")
System_Ext(autohuurService, "Autohuur service", "Service zoals Sixt of Hertz voor het huren van vervoer")
System_Ext(voedselService, "Voedsel service", "Service zoals TakeAway voor het bestellen van eten en drinken")
System_Ext(identityProviderService, "Identity provider", "Service zoals Google of Facebook voor het inloggen")
System_Ext(paymentService, "Betaal service", "Service zoals PayPal of iDeal voor het betalen")
System_Ext(noticationService, "Notificatie service", "Service zoals e-mail of SMS voor het versturen van notificaties")
System_Ext(identityProviderService, "Identity provider service", "Service zoals Google of Facebook voor het inloggen")

' Klant relaties
Rel(klant, frontend, "Stelt reis samen met", "HTTP")
Rel(noticationService, klant, "Stuurt notificaties naar")

' ReisAgent relaties
Rel(reisAgent, frontend, "Helpt klant via", "HTTP")

' Triptop relaties
Rel(frontend, backend, "Communiceert met", "JSON/HTTP")
Rel(frontend, identityProviderService, "Genereert token met", "HTTPS")
Rel_L(backend, database, "Leest en schrijft data naar")

'API relaties
Rel_R(backend, overnachtingService, "Boekt overnachting met", "HTTPS")
Rel_U(backend, vervoerService, "Regelt vervoer met", "HTTPS")
Rel_U(backend, activiteitService, "Plant activiteiten met", "HTTPS")
Rel_U(backend, autohuurService, "Huurt vervoer met", "HTTPS")
Rel(backend, voedselService, "Regelt voedsel met", "HTTPS")
Rel(backend, identityProviderService, "Authenticeert/autoriseert met", "HTTPS")
Rel(backend, paymentService, "Betaalt met", "HTTPS")
Rel(backend, noticationService, "Stuurt notificaties via")
@enduml
