@startuml

autonumber

actor Reiziger
participant "TransportController:\nTransportController" as TC
participant "TransportService:\nTransportService" as TS
participant "AdapterFactory:\nAdapterFactory" as AF
participant "ITransportAdapter:\nITransportAdapter" as Adapter
participant "Trip:\nTrip"

Reiziger -> TC: getAvailableTrips(tripRequest)
TC -> TS: getAvailableTrips(tripRequest)
TS -> TS: transportType = extractTransportType(tripRequest)
TS -> AF: adapter = getTransportAdapter(transportType)

alt Connection Established with API
    TS -> Adapter: trips = adapter.getAvailableTrips(tripRequest)
    TS -> TC: trips
    TC -> Reiziger: trips
else Connection Failure with API
    Adapter -> TS: error("Could not retrieve data")
    TS -> TC: error("Could not retrieve data")
    TC -> Reiziger: error("Could not retrieve data")
end

@enduml
